config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'sessions#new'
  get    '/home',           to: 'static_pages#home'
  get    '/signup',         to: 'users#new'
  get    '/login',          to: 'sessions#new'
  post   '/login',          to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'
  get     'how_to_use',     to: 'static_pages#how_to_use'
  get    '/new_post',       to: 'microposts#new'
  get    '/microposts',     to: 'static_pages#home'
  get    '/location_posts', to: 'location_posts#index'
  get    '/location_posts/count', to: 'location_posts#count'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts do
    resource :likes, only: %i[create destroy]
  end

  resources :maps, only: [:index]
  resources :likes, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :microposts,          only: %i[create destroy show]
  resources :relationships,       only: %i[create destroy]
end

app/models/like.rb
# frozen_string_literal: true

# Like
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

# LikesController
class LikesController < ApplicationController
  before_action :logged_in_user

  def index
    @liked_microposts = current_user.liked_microposts.paginate(page: params[:page], per_page: 45)
  end

  def create
    @micropost = Micropost.find(params[:micropost_id])
    Like.create(user_id: current_user.id, micropost_id: @micropost.id) 
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update("like_buttons_#{params[:micropost_id]}",
                                                 partial: 'likes/like', locals: { micropost: @micropost })
      end
    end
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    @micropost_like = Like.find_by(user_id: current_user.id, micropost_id: @micropost.id)
    @micropost_like&.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update("like_buttons_#{params[:micropost_id]}",
                                                 partial: 'likes/like', locals: { micropost: @micropost })
      end
    end
  end
end

app/views/likes/_like.html.erb
  <% # いいね　パーシャル %>
  <div class="like-container">
    <% if micropost.liked?(current_user) %>
        <%= button_to micropost_likes_path(micropost.id), method: :delete, data: { turbo_frame: "like_buttons_#{micropost.id}" } do %>
            <span class="active-like">❤︎</span> 
        <% end %>
    <% else %>
        <%= button_to micropost_likes_path(micropost.id), method: :post, data: { turbo_frame: "like_buttons_#{micropost.id}" } do %>
            <span class="passive-like">❤︎</span> 
        <% end %>
    <% end %>
</div>

app/views/likes/index.html.erb
 <% # いいね一覧画面 %>
 <div class="profile-name">
    <%= current_user.name %>
  </div>

    <div style="margin-bottom: 10px;"></div>

    <%= link_to "プロフィールの編集", edit_user_path(current_user), class: "edit-user-link" %>

    <div style="margin-bottom: 10px;"></div>

    <% @user ||= current_user %>
    <div class="stats">
      <% # フォロー数 %>
      <a href="<%= following_user_path(@user) %>">
        <span id="following">
          <%= @user.following.count %>
        </span>
        フォロー中
      </a>

      <% # フォロワー数 %>
      <a href="<%= followers_user_path(@user) %>">
        <span id="followers">
          <%= @user.followers.count %>
        </span>
        フォロワー
      </a>
    </div>

     <div style="margin-bottom: 20px;"></div>

    <div class="show-profile-link-container">
      <%= link_to "投稿一覧", current_user, class: "show-profile-link-inactive" %>
      <%= link_to "いいね欄", likes_path, class: "show-profile-link-active" %>
    </div>

    <% if @liked_microposts.empty? %>
      <div style="margin-bottom: 30px;"></div>
      <p class="no-posts-message">お気に入りの投稿を見つけて、いいねを押してみましょう！</p>
      <%= link_to '投稿を見てみる', home_path, class: 'share-photo-button' %>
    <% else %>
      <div class="profile-microposts-container">
        <% @liked_microposts.each do |micropost| %>
          <%= link_to (image_tag micropost.image if micropost.image.attached?), micropost_path(micropost), data: {"turbo" => false} %>
        <% end %>
      </div>
      <div class="pagination-container">
        <%= will_paginate @liked_microposts, previous_label: '前へ', next_label: '次へ', inner_window: 0, outer_window: 0 %>
      </div>
    <% end %>