config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'sessions#new'
  get    '/home',           to: 'static_pages#home'
  get    '/signup',         to: 'users#new'
  get    '/login',          to: 'sessions#new'
  post   '/login',          to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'
  get     'how_to_use',     to: 'static_pages#how_to_use'
  get    '/new_post',       to: 'microposts#new'
  get    '/microposts',     to: 'static_pages#home'
  get    '/location_posts', to: 'location_posts#index'
  get    '/location_posts/count', to: 'location_posts#count'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts do
    resource :likes, only: %i[create destroy]
  end

  resources :maps, only: [:index]
  resources :likes, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :microposts,          only: %i[create destroy show]
  resources :relationships,       only: %i[create destroy]
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :liked_microposts, through: :likes, source: :micropost
  has_many :microposts, dependent: :destroy
  has_many :active_relationships,  class_name:  'Relationship', foreign_key: 'follower_id', dependent:   :destroy
  has_many :passive_relationships, class_name:  'Relationship', foreign_key: 'followed_id', dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token

  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost:)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # セッションハイジャック防止のためにセッショントークンを返す
  def session_token
    remember_digest || remember
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーのステータスフィードを返す
  def feed
    following_ids = 'SELECT followed_id FROM relationships WHERE  follower_id = :user_id'
    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
             .includes(:user, image_attachment: :blob)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user unless self == other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    following.delete(other_user)
  end

  # 現在のユーザーが他のユーザーをフォローしていればtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # フォローしているユーザーの投稿を返す
  def following_feed
    following_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
             .includes(:user, image_attachment: :blob)
  end

  private

  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# ApplicationController
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index show edit update destroy following followers]
  before_action :correct_user,   only: %i[edit update]
  before_action :admin_user,     only: :destroy

  def index
    @users = if params[:search].present?
               User.where('name LIKE ?', "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
             else
              User.paginate(page: params[:page], per_page: 10)
             end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 45)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'アカウントを有効にするには、メールを確認してください'
      redirect_to root_url
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'プロフィールを更新しました'
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'アカウントを削除しました'
    redirect_to users_url, status: :see_other
  end

  def following
    @title = 'フォロー中'
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  def followers
    @title = 'フォロワー'
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  private

  # 送信可能なパラメータか確認する
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # 正しいユーザーかどうかを確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url, status: :see_other) unless current_user?(@user)
  end

  # 管理者かどうかを確認
  def admin_user
    redirect_to(root_url, status: :see_other) unless current_user.admin?
  end
end

app/views/users/_user.html.erb
<% # ユーザー パーシャル%>
<li>
  <div class="user-name">
    <%= link_to user.name, user %>
  </div>
  <div class="user-delete">
    <% if current_user.admin? && !current_user?(user) %> 
      <%= link_to "削除する", user, data: { "turbo-method": :delete, "turbo_confirm": "削除してもよろしいですか？" }%>
    <% end %>
  </div>
</li>

app/views/users/edit.html.erb
<% # プロフィール編集画面 %>

  <%= form_with(model: @user) do |f| %>
  <div class="edit-user-title">プロフィールを編集</div>

    <%= f.label :name, "ユーザーネーム", class: 'edit-user-label' %>
    <%= f.text_field :name, class: 'edit-user-field' %>
    <%= f.object.errors[:name].any? ? content_tag(:div, f.object.errors[:name].join(", "), class: "error-message") : "" %>

    <%= f.label :email, "メールアドレス", class: 'edit-user-label' %>
    <%= f.email_field :email, class: 'edit-user-field' %>
    <%= f.object.errors[:email].any? ? content_tag(:div, f.object.errors[:email].join(", "), class: "error-message") : "" %>

    <%= f.label :password, "パスワード", class: 'edit-user-label' %>
    <%= f.password_field :password, class: 'edit-user-field' %>
    <%= f.object.errors[:password].any? ? content_tag(:div, f.object.errors[:password].join(", "), class: "error-message") : "" %>

    <%= f.label :password_confirmation, "パスワード再入力", class: 'edit-user-label' %>
    <%= f.password_field :password_confirmation, class: 'edit-user-field' %>
    <%= f.object.errors[:password_confirmation].any? ? content_tag(:div, f.object.errors[:password_confirmation].join(", "), class: "error-message") : "" %>


    <div style="margin-bottom: 50px;"></div>

      <%= f.submit "保存", class: "edit-user-btn" %>
  <% end %>

app/views/users/index.html.erb
<% #　アカウント検索画面 %>
  <%= form_tag(users_path, method: :get) do %>
  <%= text_field_tag :search, params[:search], class: 'user-search-field', placeholder: 'アカウントを検索' %>
  <% end %>

  <ul class="users">
    <%= render @users %>
  </ul>
  <div class="pagination-container"> 
  <%= will_paginate @users, previous_label: '前へ', next_label: '次へ', inner_window: 0, outer_window: 0 %>
  </div>

app/views/users/new.html.erb
<% #アカウント登録画面 %>
<% content_for :hide_header, true %>

<div class="login-container">
  <div class="login-logo">spot snap</div>
  <div style="margin-bottom: 20px;"></div>
  <span style="font-size: 0.9em; font-weight: 600;">ユーザー情報を入力してください。</span>
  <%= form_with(model: @user) do |f| %>
    <%= f.text_field :name, class: 'login-form', placeholder: "ユーザーネーム" %>
    <%= f.object.errors[:name].any? ? content_tag(:div, f.object.errors[:name].join(", "), class: "error-message") : "" %>

    <%= f.email_field :email, class: 'login-form', placeholder: "メールアドレス" %>
    <%= f.object.errors[:email].any? ? content_tag(:div, f.object.errors[:email].join(", "), class: "error-message") : "" %>

    <%= f.password_field :password, class: 'login-form', placeholder: "パスワード" %>
    <%= f.object.errors[:password].any? ? content_tag(:div, f.object.errors[:password].join(", "), class: "error-message") : "" %>

    <%= f.password_field :password_confirmation, class: 'login-form', placeholder: "パスワード再入力" %>
    <%= f.object.errors[:password_confirmation].any? ? content_tag(:div, f.object.errors[:password_confirmation].join(", "), class: "error-message") : "" %>

    <div style="margin-bottom: 50px;"></div>

    <%= f.submit "登録", class: "grey-btn" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% # アカウント画面 %>
<div class="profile-name">
  <%= @user.name %>
</div>

  <div style="margin-bottom: 10px;"></div>

<% if @user == current_user %>
  <%= link_to "プロフィールの編集", edit_user_path(current_user), class: "edit-user-link" %>
<% end %>
<% if logged_in? && !current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= form_with(model: current_user.active_relationships.find_by(followed: @user), html: { method: :delete }) do |f| %>
        <%= f.submit "フォロー中", class: "unfollow-btn" %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.active_relationships.build) do |f| %>
        <div><%= hidden_field_tag :followed_id, @user.id %></div>
        <%= f.submit "フォロー", class: "follow-btn" %>
      <% end %>
    <% end %>
  </div>
<% end %>

  <div style="margin-bottom: 10px;"></div>

<% @user ||= current_user %>
<div class="stats">
  <% # フォロー数 %>
  <a href="<%= following_user_path(@user) %>">
    <span id="following">
      <%= @user.following.count %>
    </span>
    フォロー中
  </a>

  <% # フォロワー数 %>
  <a href="<%= followers_user_path(@user) %>">
    <span id="followers">
      <%= @user.followers.count %>
    </span>
    フォロワー
  </a>
</div>

  <div style="margin-bottom: 20px;"></div>

<% if @user == current_user %>
  <div class="show-profile-link-container">
    <%= link_to "投稿一覧", current_user, class: "show-profile-link-active" %>
    <%= link_to "いいね欄", likes_path, class: "show-profile-link-inactive" %>
  </div>
<% end %>

<% if @microposts.empty? && @user == current_user %>
  <div style="margin-bottom: 30px;"></div>
  <p class="no-posts-message">あなたのお気に入りの場所をシェアして、プロフィールを充実させましょう！</p>
  <%= link_to '投稿してみる', new_micropost_path, class: 'share-photo-button' %>
<% else %>
  <div class="profile-microposts-container">
    <% @microposts.each do |micropost| %>
      <%= link_to (image_tag micropost.image if micropost.image.attached?), micropost_path(micropost), data: {"turbo" => false} %>
    <% end %>
  </div>
<% end %>

<div class="pagination-container">
  <%= will_paginate @microposts, previous_label: '前へ', next_label: '次へ', inner_window: 0, outer_window: 0 %>
</div>

app/views/users/show_follow.html.erb
<% # フォロー/フォロワー一覧画面 %>

<% # アカウント名 %>
<section class="follow-account">
  <%= @user.name %>
</section>

<div style="margin-bottom: 10px;"></div>

<div class="follow-status">
  <% # フォロー数 %>
  <a href="<%= following_user_path(@user) %>">
    <span id="following">
      <%= @user.following.count %>
    </span>
    フォロー中
  </a>

  <% # フォロワー数 %>
  <a href="<%= followers_user_path(@user) %>">
    <span id="followers">
      <%= @user.followers.count %>
    </span>
    フォロワー
  </a>
</div>

<div style="margin-bottom: 50px;"></div>

 <div class="follow-title">
  <%= @title %>
</div>

  <ul class="users">
    <%= render @users %>
  </ul>
   <div class="pagination-container"> 
  <%= will_paginate @users, previous_label: '前へ', next_label: '次へ', inner_window: 0, outer_window: 0 %>
  </div>