config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'sessions#new'
  get    '/home',           to: 'static_pages#home'
  get    '/signup',         to: 'users#new'
  get    '/login',          to: 'sessions#new'
  post   '/login',          to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'
  get     'how_to_use',     to: 'static_pages#how_to_use'
  get    '/new_post',       to: 'microposts#new'
  get    '/microposts',     to: 'static_pages#home'
  get    '/location_posts', to: 'location_posts#index'
  get    '/location_posts/count', to: 'location_posts#count'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts do
    resource :likes, only: %i[create destroy]
  end

  resources :maps, only: [:index]
  resources :likes, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: %i[new create edit update]
  resources :microposts,          only: %i[create destroy show]
  resources :relationships,       only: %i[create destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <% # 基本設定 %>
  <head>
    <title>SpotSnap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&libraries=places&loading=async" defer></script>
    <link rel="icon" href="<%= asset_path 'spotsnap.png' %>" sizes="64x64" type="image/png">
  </head>
  <body>
    <% unless content_for?(:hide_header) %>
      <header class="header">
        <div class="logo"><%= link_to "Spot Snap", home_path, data: { "turbo" => false } %></div>
        <div class="hamburger-menu">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </header>
      <div class="overlay"></div>
      <aside class="sidebar">
        <ul>
          <li><%= link_to new_post_path, data: {"turbo" => false} do %>
            <%= image_tag("post.png", size: 30) %><span class="sidebar-text">投稿</span> 
          <% end %></li>
          <li><%= link_to maps_path, data: {"turbo" => false} do %>
            <%= image_tag("map.png", size: 30) %><span class="sidebar-text">マップ</span>
          <% end %></li>
          <li><%= link_to users_path do %>
            <%= image_tag("search.png", size: 30) %><span class="sidebar-text">検索</span>
          <% end %></li>
          <li><%= link_to current_user do %>
            <%= image_tag("account.png", size: 30) %><span class="sidebar-text">プロフィール</span>
          <% end %></li>
          <li><%= link_to how_to_use_path do %>
            <%= image_tag("how_to_use.png", size: 30) %><span class="sidebar-text">使い方</span>
          <% end %></li>
          <li class="logout"><%= link_to logout_path, data: { "turbo-method": :delete ,"turbo-confirm": "ログアウトしてもよろしいですか？"} do %>
            <%= image_tag("logout.png", size: 30) %><span class="sidebar-text">ログアウト</span>
          <% end %></li>
        </ul>
      </aside>
    <% end %> 

    <div class="container">
      <% # フラッシュメッセージ表示 %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>